NEW : Compatibilité "Équipement" et "Commande client depuis commande fournisseur multi-société"
ATM-Consulting/dolibarr_module_dispatch pull request #58
Opened 2020-09-24 15:35 UTC by atm-kevin

# NEW T2476 / Compatibilité "Équipement" et "Commande client depuis commande fournisseur multi-société"

## Ventilation des produits non sérialisés & équipements (produits sérialisés) 
Déclenchement de la gestion des équipements lors de l'action de réception d'une commande fournisseur via le bouton "Recevoir Produits".
Création des équipements (& Mouvements de stock) présents dans la Commande Client liée à la Commande Fournisseur

2020-09-28 12:43 UTC, atm-quentin commented on class/actions_dispatch.class.php
> +		$sql = "SELECT c.rowid FROM llx_commande AS c, llx_commandedet AS cd WHERE c.ref_client = '".$object->ref. "' AND c.rowid = cd.fk_commande ORDER BY cd.rowid";
llx_ en dur

2020-09-28 12:43 UTC, atm-quentin commented on class/actions_dispatch.class.php
> +		$shipmentsSql = "SELECT * FROM llx_commande AS c, llx_expedition AS e WHERE c.ref = '".$orderFromSupplierOrder->ref. "' AND c.ref_client = e.ref_customer";
idem

2020-09-28 12:48 UTC, atm-quentin commented on class/actions_dispatch.class.php
> +		$sql = "SELECT c.rowid FROM llx_commande AS c, llx_commandedet AS cd WHERE c.ref_client = '".$object->ref. "' AND c.rowid = cd.fk_commande ORDER BY cd.rowid";
utilise des jointures sql

2020-09-28 12:49 UTC, atm-quentin commented on class/actions_dispatch.class.php
> +		$shipmentsSql = "SELECT * FROM llx_commande AS c, llx_expedition AS e WHERE c.ref = '".$orderFromSupplierOrder->ref. "' AND c.ref_client = e.ref_customer";
aie aie aie, utilise des jointures sql, pour lier la commande à l'exped il faudrait mieux utiliser la table element_element

2020-09-28 12:49 UTC, atm-quentin commented on class/actions_dispatch.class.php
> +		//var_dump($object->orderFromSupplierOrder);
clean stp

2020-09-28 12:50 UTC, atm-quentin commented on class/actions_dispatch.class.php
> +		//var_dump($object->orderFromSupplierOrder);
clean cette fonction useless

2020-09-28 12:50 UTC, atm-quentin commented on class/actions_dispatch.class.php
> +		//var_dump("dump dispatch action");
clean

2020-09-28 12:52 UTC, atm-quentin commented on js/dispatch.js.php
> +			console.log(d);
clean

2020-09-28 12:54 UTC, atm-quentin commented on js/dispatch.js.php
> +		console.log(document.getElementsByClassName(className).length == 0);
clean

2020-09-28 12:54 UTC, atm-quentin commented on js/dispatch.js.php
> +		let comFourn = $(this).attr('data-commandFourn-id');
$(this).data pour récup des 'data-'

2020-09-28 12:56 UTC, atm-quentin commented on js/dispatch.js.php
> +				console.log("Success !!!");
clean

2020-09-28 12:56 UTC, atm-quentin commented on js/dispatch.js.php
> +				console.log(data);
clean

2020-09-28 12:57 UTC, atm-quentin commented on js/dispatch.js.php
> +
t'étais bien parti pour faire de la gestion d' erreur, dommage ..

2020-09-28 12:58 UTC, atm-quentin commented on js/dispatch.js.php
> +					self
à quoi sert ce self ?

2020-09-28 12:58 UTC, atm-quentin commented on js/dispatch.js.php
> +			error: function (err) {
idem

2020-09-28 12:59 UTC, atm-quentin commented on reception.php
> +	dol_include_once('/fourn/class/fournisseur.commande.class.php' );
require_once DOL_DOCUMENT_ROOT

2020-09-28 13:00 UTC, atm-quentin commented on reception.php
> +		setEventMessage($langs->trans('DeletedLine'));
merci

2020-09-28 13:01 UTC, atm-quentin commented on reception.php
> +	$tOrderLine = GETPOST('TOrderLine');
t majuscule stp

2020-09-28 13:30 UTC, atm-quentin commented on reception.php
> +					$asset->set_date('date_reception', $_REQUEST['date_recep']);
GETPOST

2020-09-28 13:31 UTC, atm-quentin commented on reception.php
> +					// $asset->contenancereel_value = 1;
clean

2020-09-28 13:40 UTC, atm-quentin commented on reception.php
> + * @param $commande
typez la phpdoc svp

2020-09-28 13:41 UTC, atm-quentin commented on reception.php
> +	if (is_supplier_Linked($conf->entity,$commande->socid)){
c'est pas très beau ce nom de fonction

2020-09-28 13:41 UTC, atm-quentin commented on reception.php
> + * @param $shipments
il manque un param

2020-09-28 13:43 UTC, atm-quentin commented on reception.php
> + * @param $shipments
manque un param typé

2020-09-28 13:44 UTC, atm-quentin commented on reception.php
> +			$currentExp->fetch($shipment->rowid);
verifiez les retours de fonction

2020-09-28 13:47 UTC, atm-quentin commented on reception.php
> + * @param $commande
typez

2020-09-28 13:48 UTC, atm-quentin commented on reception.php
> +					<td>test
test

2020-09-28 13:48 UTC, atm-quentin commented on reception.php
> + * @param $commandefourn
typez

2020-09-28 13:49 UTC, atm-quentin commented on reception.php
> +function _addCommandedetLine(&$PDOdb,&$TImport,&$commandefourn,$refproduit,$numserie,$imei,$firmware,$lot_number,$quantity,$quantity_unit,$dluo=null,$k=null,$entrepot=null,$comment=''){
phpdoc

2020-09-28 13:49 UTC, atm-quentin commented on reception.php
> +	//pre($TImport,true);
clean

2020-09-28 13:50 UTC, atm-quentin commented on reception.php
> +function searchProductInCommandeLine($array, $idprod)
phpdoc

2020-09-28 13:51 UTC, atm-quentin commented on reception.php
> +function _show_product_ventil(&$TImport, &$commande,&$form) {
phpdoc

2020-09-28 13:52 UTC, atm-quentin commented on reception.php
> +						console.log(fk_product);
clean

2020-09-28 13:54 UTC, atm-quentin commented on reception.php
> +			var prefix = TMatches[1] ? TMatches[1] : ''; // Si undefined car nombre pur => chaine vide
essaie d'utiliser let plutot que var quand c'est possible

2020-09-28 13:58 UTC, atm-quentin commented on reception.php
> +function is_supplier_Linked($entity,$socid){
phpdoc

2020-09-28 13:59 UTC, atm-quentin commented on reception.php
> +		$sql = "SELECT DISTINCT te.rowid , te.fk_soc , te.entity , te.fk_entity FROM " . MAIN_DB_PREFIX . "societe as s , " . MAIN_DB_PREFIX . "thirdparty_entity as te WHERE ";
jointure

2020-09-28 14:01 UTC, atm-quentin commented on reception.php
> +		return !is_null($db->fetch_object($db->query($sql)));
est-ce que tu peux faire ça en plusieurs lignes + utilise db num rows plutot + pourquoi tu sélectionnes tous ces champs là?

2020-09-28 14:02 UTC, atm-quentin commented on reception.php
> +function _set_treated_expedition_extrafield($idexpe, $shipmentEntity) {
phpdoc

2020-09-28 14:02 UTC, atm-quentin commented on reception.php
> +function _isTreatedExpAlreadyExists($shipments) {
phpdoc

2020-09-28 14:03 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +dol_include_once('/expedition/class/expedition.class.php' );
require once

2020-09-28 14:04 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +	foreach ($currentExpe->lines as $currentLineExp) {
if ! empty

2020-09-28 14:04 UTC, atm-quentin commented on script/interface_expedition_handler.php
> + * @param $currentExpe
typez

2020-09-28 14:05 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +		$sql = "SELECT * FROM ".MAIN_DB_PREFIX."expeditiondet_asset AS ea, ".MAIN_DB_PREFIX."assetatm AS AT WHERE fk_expeditiondet = ".$currentLineExp->id." AND ea.fk_asset = AT.rowid" ;
jointure + AT en maj ? Si le soucis c'est le mot clé "at", mais pas des majs mais utilise un autre mot clé

2020-09-28 14:07 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +function formatDisplayTableProductsHeader(){
phpdoc

2020-09-28 14:08 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +function formatDisplayTableProducts(&$currentExp,$entity, $idCommand){
phpdoc

2020-09-28 14:08 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +	dol_include_once('/core/class/html.form.class.php');
require_once

2020-09-28 14:09 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +	dol_include_once('/core/class/html.form.class.php');
de plus tu n'utilise pas la classe Form

2020-09-28 14:09 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +	foreach ($currentExp->lines as $k=>$line) {
if ! empty

2020-09-28 14:10 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +		}else {$fk_asset = "standardProduct";}
peux tu enlever les accolades stp

2020-09-28 14:11 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +		dol_include_once('/product/class/html.formproduct.class.php');
require_once

2020-09-28 14:11 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +				//$output .='<td>'.$form->calendrier('','TLine['.$k.'][dluo]', date('d/m/Y',strtotime($line['dluo']))).'</td>';
useless

2020-09-28 14:11 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +//						echo '<td>'. ($commande->statut < 5) ? $formproduct->select_measuring_units('TLine['.$k.'][quantity_unit]','weight',$line['quantity_unit']) : measuring_units_string($line['quantity_unit'],'we
tu as vidé le if

2020-09-28 14:12 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +	$soc->fetch($currentExp->socid);
retour de fonction

2020-09-28 14:12 UTC, atm-quentin requested changes
gl hf

2020-09-29 10:24 UTC, atm-kevin commented on js/dispatch.js.php
> +		let comFourn = $(this).attr('data-commandFourn-id');
Pourquoi ? 
Les deux sont valables $this).data et $(this).attr('data'...)

2020-09-29 10:39 UTC, atm-kevin commented on reception.php
> +	if (is_supplier_Linked($conf->entity,$commande->socid)){
Une suggestion ?

2020-09-29 12:17 UTC, atm-kevin commented on script/interface_expedition_handler.php
> +	foreach ($currentExpe->lines as $currentLineExp) {
if (!empty) de $currentExpe ?

2020-09-29 12:25 UTC, atm-kevin commented on script/interface_expedition_handler.php
> +	dol_include_once('/core/class/html.form.class.php');
Par rapport à la classe Form, elle n'a pas de méthode "hidden" j'ai l'impression
C'est pour cela qu'on a utiliser $form = new TFormCore( ) et non $form = new Form( )

2020-09-29 12:32 UTC, atm-quentin commented on reception.php
> +	if (is_supplier_Linked($conf->entity,$commande->socid)){
isSupplierLinked ou is_supplier_linked :p

2020-09-29 12:32 UTC, atm-quentin commented on reception.php
> +	if (is_supplier_Linked($conf->entity,$commande->socid)){
pas de melande camelcase/snakecase

2020-09-29 12:33 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +	foreach ($currentExpe->lines as $currentLineExp) {
de $currentExpe->lines

2020-09-29 12:33 UTC, atm-quentin commented on script/interface_expedition_handler.php
> +	dol_include_once('/core/class/html.form.class.php');
ça ne sert à rien d'inclure la classe form si tu n'utilises pas new Form, FormCore c'est du abricot

2020-09-29 12:41 UTC, atm-quentin commented on js/dispatch.js.php
> +		let comFourn = $(this).attr('data-commandFourn-id');
dans ton cas il n'y a pas de difference, mais puisqu'on utilise un item data- autant utiliser la fonction qui les manipule

2020-09-30 09:21 UTC, atm-kevin commented on script/interface_expedition_handler.php
> +	dol_include_once('/core/class/html.form.class.php');
OK merci, vu avec John : tous les modules seront updatés à l'avenir pour ne plus inclure ces fonctionnalités abricot 
Pour cette feature, on laisse notre $form->hidden comme ça ;)

2020-10-05 09:18 UTC, closed without merging