NEW T2476 Ventilation produits/équipement multicompany OFSOM
ATM-Consulting/dolibarr_module_dispatch pull request #59
Opened 2020-10-05 09:27 UTC by atm-kevin

# NEW T2476 Ventilation produits/équipement multicompany OFSOM

> Lien vers PR précédente (partie d'une branche différente) dont les retours ont été géré sur une autre branche "ultimate" : 

https://github.com/ATM-Consulting/dolibarr_module_dispatch/pull/58

2020-10-06 08:54 UTC, atm-john requested changes

2020-10-06 08:54 UTC, atm-john commented on class/actions_dispatch.class.php
> +		dol_include_once('/commande/class/commande.class.php' );
ATTENTION : il n'y a pas de vérification du contexte

2020-10-06 08:54 UTC, atm-john commented on core/modules/moddispatch.class.php
> +		$this->version = '2.2.0';
ça c'est pas possible !

2020-10-06 08:54 UTC, atm-john commented on core/modules/moddispatch.class.php
> +			,'js' => array('/dispatch/js/dispatch.js.php'),
Tu en a vraiment besoin partout de ce js ?

2020-10-06 08:54 UTC, atm-john commented on js/dispatch.js.php
> +		$('.ventileBtn').removeClass('butActionRefused');
.ventileBtn => Même constant que pour JP, quand tu utilise une classe pour trigger une action essaye de faire en sorte que la classe n'ait pas nom trop générique surtout si tu charge ton js sur toutes les pages.

2020-10-06 08:54 UTC, atm-john commented on js/dispatch.js.php
> +		$('.ventileBtn').removeClass('butActionRefused');
idem

2020-10-06 08:54 UTC, atm-john commented on js/dispatch.js.php
> +		if (document.getElementsByClassName(className).length == 0) {
Note : si tu utilise jquery ça fait bizarre que tu repasse sur du vanilla

`if ($(className).length == 0) {`
normalement ça marche aussi

ça veut pas dire que tu doit le changer

2020-10-06 08:54 UTC, atm-john commented on js/dispatch.js.php
> +			d = document.createElement("div");
idem pour info :

`$(".tabBar").append('<div class="'+className+'" ></div>');`

doit marcher aussi 

note : avec ce code tu part du principe qu'il n'y qu'un seul tabBar ce qui n'est pas forcement le cas, l'a tu pris en compte ?

2020-10-06 08:54 UTC, atm-john commented on js/dispatch.js.php
> +			}
tu ne traite pas les erreurs ?

2020-10-06 08:54 UTC, atm-john commented on reception.php
> +		header('location:receptionofsom.php?id='.$id);
j'ai un doute sur la redirection es-tu sur qu'elle fonctionne  quelque soit l'url du Dolibarr ?

2020-10-06 08:54 UTC, atm-john commented on reception.php
> +	$res = $db->query($sql);
Tu part du principe que ta requête sql est infaillible .
comment fait tu pour gérer l'erreur ?

pourquoi ne pas utiliser COUNT() ?

2020-10-06 08:54 UTC, atm-john commented on receptionofsom.php
> +function _addCommandedetLine(&$PDOdb,&$TImport,&$commandefourn,$refproduit,$numserie,$imei,$firmware,$lot_number,$quantity,$quantity_unit,$dluo=null,$k=null,$entrepot=null,$comment=''){
Note si tes fonctions préfixée par _ sont des copié collé ça vaut peut-être le coup de factoriser ou de le mettre nà minima en commentaire en mode guirlande histoire que si l'on fixe qq chose dans ces fonctions que ce soit fait partout

2020-10-06 08:54 UTC, atm-john commented on script/interface_expedition_handler.php
> +function getEquipmentsFromSupplier(&$currentExpe)
si ta fonction est exclusive à ce script, préfixe là avec _
idem pour le reste

2020-10-07 08:45 UTC, atm-kevin commented on js/dispatch.js.php
> +			d = document.createElement("div");
Comme le paramètre $notab = -1 , la fonction dol_fiche_head créée une <div> avec la classe "tabBar"

2020-10-13 14:09 UTC, atm-john commented on class/actions_dispatch.class.php
> +
là tu ne vérifie pas si le query est un success

2020-10-13 14:18 UTC, atm-john commented on js/dispatch.js.php
> +	$(document).on("click", ".butActionDelete", function (e) {
Il faut être sur que ton fichier JS n'est pas appeler sur d'autres pages que celle que l'on souhaite car la classe  .butActionDelete est commune il me semble, ça ouvre des possibilités aux comportement bizarres.

Une bonne solution peut être de renommer le fichier js pour éviter qu'il ne porte simplement le nom du module.
Sinon dans un an un autre dev va ajouter lui aussi un bout de code, dont il va avoir besoin partout et a final ton bout de code va s’exécuter sur chaque click sur un bouton delete

2020-10-13 14:24 UTC, atm-john commented on js/dispatch.js.php
> +		let data = {
évite les noms de variable qui permettent la confusion.
ici tu as data pour 3 contextes différents.

utilise plutôt 
`let dataToSend =`

2020-10-14 08:27 UTC, atm-kevin commented on js/dispatch.js.php
> +	$(document).on("click", ".butActionDelete", function (e) {
Ok merci, finalement on a opté pour l'insertion d'un script type text/javascript dans le code au lieu d'avoir un dossier JS

2020-10-14 08:56 UTC, atm-kevin commented on receptionofsom.php
> +	for ($i = 0; $i < $Tlength; $i++){
Si on traite l'hydratation de $TImport à l'intérieur du foreach, ça plante et il n'y a pas de mouvement de stock des équipements.
On a donc pris le parti de préparer le $TImport dans une première étape (le for).

2020-10-15 09:47 UTC, atm-john requested changes

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +				$prod->fetch($line['fk_product']);
et si pas de fetch ?

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +				$asset->serial_number = ($line['numserie']) ? $line['numserie'] : $asset->getNextValue($PDOdb);
a vérifier que getNextValue ne renvoi pas une erreur et gérer le cas

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +				$fk_entrepot = (!empty($line['fk_warehouse']) && $line['fk_warehouse'] > 0) ? $line['fk_warehouse'] : GETPOST('id_entrepot');
bon c'est pas vous mais récupérer un int sans checker que c'est un int, c'est faire confiance à l'internaute...

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +							}
gestion de l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +		$currentExp->fetch($shipment->rowid);
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +		$current_cmdFourn->fetch($idCmdFourn);
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +			$extra->fetch_name_optionals_label($shipment->table_element);
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +			}
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +		$PDOdb->Execute($sql);
et pim !

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +	$recepdetail->save($PDOdb);
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +	}
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +		$TOrderLine = GETPOST('TOrderLine');
le check none passe par defaut en alphanohtml en v11 oiu 12 de doli

mais la c''est un tableau ...
du coup si pas typé risque de recupérer une string et pas un tableau

donc vérifier le type de TOrderLine c'est bien un array ou mettre un check de type none

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +	$currentExp->fetch($idexpe);
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +	$currentExp->updateExtraField('customer_treated_shipment');
gérer l'erreur

2020-10-15 09:47 UTC, atm-john commented on receptionofsom.php
> +	$resultset= $db->query($sql);
gérer l'erreur avec le -1

2020-10-15 13:54 UTC, atm-kevin commented on receptionofsom.php
> +				$asset->serial_number = ($line['numserie']) ? $line['numserie'] : $asset->getNextValue($PDOdb);
La fonction d'origine (get_next_value) teste déjà les erreurs.
Et dans la fonction **getNextValue**, il est noté :

$ref = get_next_value($db,$mask,'assetatm','serial_number','',$objSoc,'','next');

if ($ref == 'ErrorBadMask') $ref = ' ' ;
   return $ref ;

Donc si une erreur est déclenchée dans cette fonction, au pire notre code renseignera $line['numserie'] avec une valeur vide.

2020-10-21 07:29 UTC, atm-john commented on class/actions_dispatch.class.php
> +	function beforePDFCreation($parameters, &$object, &$action, $hookmanager)
Et la PHP Doc ????

2020-10-21 08:13 UTC, atm-john commented on receptionofsom.php
> +function entetecmd(&$commande)
PHP DOC

2020-10-21 08:14 UTC, atm-john commented on receptionofsom.php
> + * @param $PDOdb
A typer

2020-10-21 08:15 UTC, atm-john commented on receptionofsom.php
> +/*
Tu as peut être fait sauter le fonctionnement de ta PHP doc avec le dernier com, a confirmer

2020-10-21 08:15 UTC, atm-john commented on receptionofsom.php
> +function printJSSerialNumberAutoDeduce() {
PHP DOC

2020-10-21 13:01 UTC, atm-john approved these changes

2020-10-21 13:30 UTC, closed without merging